name: water
description: An implementation of HydratedStorage using Hive, a fast and lightweight key-value database
version: 1.1.1
homepage: https://github.com/arnemolland/water

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  path_provider: ^1.6.5
  hive: ^1.4.1+1
  crypto: ^2.1.3
  hydrated_bloc:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

dependency_overrides:
  pedantic: ^1.9.0
